version: '3.8'

services:
    db:
        image: mysql:5.7
        container_name: "raffle-tg-db"
        restart: always
        tty: true
        ports:
            - "3366:3306"
        environment:
            MYSQL_DATABASE: "${DB_DATABASE}"
            MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        volumes:
            - ./docker/dbdata:/var/lib/mysql
            - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
